version: "3"
services:
  kafka:
    image: confluentinc/cp-kafka:5.0.0-2
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0-2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14267"
      - "14268:14268"
      - "14269"
      - "16686:16686"
      - "16687"
      - "9411:9411"
    restart: on-failure
